const ruCommon = {
  header: {
    reader: 'Ридер',
    backHome: 'Назад на главную',
  },
  home: {
    badge: 'Помощник для чтения на немецком',
    title: 'Читайте книги на немецком ясно и без лишнего трения.',
    subtitle:
      'peardread удерживает внимание на тексте и помогает быстро понимать каждое важное слово.',
    ctaUpload: 'Загрузить книгу',
    ctaDemo: 'Попробовать демо',
    previewLabel: 'Превью ридера',
    translationLabel: 'Перевод',
    features: {
      uploadTitle: 'Загрузите текст',
      uploadDescription:
        'Начните с TXT или EPUB и откройте книгу за несколько секунд.',
      focusTitle: 'Сохраняйте фокус',
      focusDescription:
        'Спокойный интерфейс ридера для сессий без отвлечений.',
      understandTitle: 'Нажмите, чтобы понять',
      understandDescription:
        'Выделяйте незнакомые слова и сразу получайте значение во время чтения.',
    },
    notesLabel: 'О продукте',
    notesTitle: 'Создан для сфокусированного чтения.',
    notes: {
      formats: 'Поддержка TXT / EPUB',
      language: 'Подсказки German to Russian',
      flow: 'Интерфейс для глубокого чтения',
    },
  },
  reader: {
    badge: 'Рабочая область ридера',
    title: 'Локальный ридер',
    subtitle: 'Загрузите файл и сразу начинайте читать.',
    ctaComingSoon: 'Открыть ридер',
  },
  readerWorkspace: {
    badge: 'Локальный ридер',
    title: 'Откройте книгу и читайте в потоке',
    subtitle:
      'Загрузите локальный файл и продолжайте чтение в спокойном интерфейсе с мгновенным mock-переводом.',
    dragActiveSubtitle: 'Отпусти файл, чтобы открыть книгу.',
    parsingSubtitle: 'Подготавливаем книгу локально. Это займет пару секунд.',
    uploadCta: 'Загрузить книгу',
    parsingCta: 'Разбираем файл',
    tryDemoCta: 'Попробовать демо',
    supportedFormats: 'Поддерживаемые форматы: TXT, MD, HTML, EPUB, FB2',
    dragActiveHint: 'Отпусти файл, чтобы открыть книгу',
    noBackendHint: 'Все работает локально в браузере. Без backend и внешних API.',
    chapter: 'Глава',
    pageLabel: 'Страница {{current}} / {{total}}',
    prevPage: 'Назад',
    nextPage: 'Вперёд',
    loadMore: 'Показать больше текста',
    epubHint: 'Для EPUB сохраняются главы для комфортного чтения по разделам.',
    translationPanel: 'Перевод',
    errors: {
      unsupported_format: 'Этот формат пока не поддерживается. Используйте TXT, MD, HTML, EPUB или FB2.',
      empty_content: 'В этом файле нет читаемого текста.',
      parse_failed: 'Не удалось разобрать файл. Попробуйте другую версию.',
      corrupted_epub: 'EPUB поврежден и не может быть открыт.',
      image_only_epub:
        'Похоже, эта книга состоит в основном из изображений или сканов, поэтому текст не удалось извлечь.',
      file_too_large: 'Файл слишком большой для локального MVP-парсинга.',
    },
  },
  demoReader: {
    title: 'Вечерняя прогулка по Берлину',
    headerHint: 'Кликните по слову или выделите короткую фразу, чтобы увидеть перевод.',
    panelTitle: 'Перевод',
    emptyState: 'Выберите слово или короткую фразу, чтобы открыть карточку перевода.',
    selectedLabel: 'Выбрано',
    russianLabel: 'Русский',
    quickTranslation: 'Быстрый перевод',
    hoverHint: 'Наведите на слово для быстрого перевода или кликните для мгновенного результата.',
    multiSelectOff: 'Выбрать несколько слов',
    multiSelectOn: 'Режим множественного выбора',
    multiSelectHint: 'Кликайте по словам, чтобы собрать фразу. Перевод обновляется сразу.',
    clearSelection: 'Очистить выбор',
    selectedPhraseLabel: 'Выбранная фраза:',
    translationUnavailable: 'Локальный перевод пока недоступен',
    translationHint: 'Попробуйте другое слово или более короткую фразу.',
    autoGeneratedNote: 'Локальная словарная запись.',
  },
  languageSwitcher: {
    en: 'EN',
    ru: 'RU',
  },
} as const

export default ruCommon
