import {
  demoParagraphs,
  demoPhraseTranslations,
  demoWordTranslations,
  type TranslationEntry,
} from './demoReaderData'

const DE_WORD_REGEX = /[\p{L}-]+/gu

export function normalizeWord(text: string) {
  return text
    .toLowerCase()
    .replace(/[“”„"']/g, '')
    .replace(/[^\p{L}-]/gu, '')
    .trim()
}

export function normalizePhrase(text: string) {
  return text
    .toLowerCase()
    .replace(/[“”„"']/g, '')
    .replace(/[^\p{L}\s-]/gu, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function toTitleCase(value: string) {
  if (!value) {
    return value
  }
  return `${value[0].toUpperCase()}${value.slice(1)}`
}

function buildAutoWordFallbackMap() {
  const map = new Map<string, TranslationEntry>()
  const words = demoParagraphs.flatMap((paragraph) => paragraph.match(DE_WORD_REGEX) ?? [])

  for (const word of words) {
    const key = normalizeWord(word)
    if (!key || map.has(key)) {
      continue
    }

    map.set(key, {
      text: toTitleCase(key),
      translation: `Демо-перевод: ${key}`,
      partOfSpeech: 'demo',
      note: 'Auto-generated fallback for demo coverage.',
    })
  }

  return map
}

const autoWordFallbackMap = buildAutoWordFallbackMap()

function generateWordCandidates(normalizedWord: string) {
  const candidates = new Set<string>([normalizedWord])

  const endings = ['en', 'er', 'em', 'es', 'e', 'n', 's']
  for (const ending of endings) {
    if (normalizedWord.endsWith(ending) && normalizedWord.length > ending.length + 2) {
      candidates.add(normalizedWord.slice(0, -ending.length))
    }
  }

  return [...candidates]
}

export function resolveDemoTranslation(
  sourceText: string,
  t: (key: string) => string,
): TranslationEntry | null {
  if (!sourceText.trim()) {
    return null
  }

  const phraseKey = normalizePhrase(sourceText)
  if (!phraseKey) {
    return null
  }

  const exactPhrase = demoPhraseTranslations[phraseKey]
  if (exactPhrase) {
    return exactPhrase
  }

  const isPhrase = phraseKey.includes(' ')
  if (isPhrase) {
    return {
      text: sourceText.trim(),
      translation: `Перевод фразы: ${phraseKey}`,
      note: t('demoReader.translationHint'),
    }
  }

  const normalizedWord = normalizeWord(sourceText)
  if (!normalizedWord) {
    return null
  }

  const candidates = generateWordCandidates(normalizedWord)
  for (const candidate of candidates) {
    const dictionaryMatch = demoWordTranslations[candidate]
    if (dictionaryMatch) {
      return dictionaryMatch
    }
  }

  const autoFallback = autoWordFallbackMap.get(normalizedWord)
  if (autoFallback) {
    return autoFallback
  }

  return {
    text: toTitleCase(normalizedWord),
    translation: `Демо-перевод: ${normalizedWord}`,
    partOfSpeech: 'demo',
    note: t('demoReader.autoGeneratedNote'),
  }
}
