const enCommon = {
  header: {
    reader: 'Reader',
    backHome: 'Back to Home',
  },
  home: {
    badge: 'German Reading Companion',
    title: 'Read books in German with clarity, not friction.',
    subtitle:
      'peardread keeps your attention on the text while helping you understand every key word.',
    ctaUpload: 'Upload a book',
    ctaDemo: 'Try demo',
    previewLabel: 'Reader preview',
    translationLabel: 'Translation',
    features: {
      uploadTitle: 'Upload your text',
      uploadDescription: 'Start with TXT or EPUB and open your book in seconds.',
      focusTitle: 'Stay focused',
      focusDescription:
        'A calm reader interface designed for distraction-free sessions.',
      understandTitle: 'Click to understand',
      understandDescription:
        'Select unknown words and quickly see the meaning while you read.',
    },
    notesLabel: 'Product notes',
    notesTitle: 'Built for focused reading sessions.',
    notes: {
      formats: 'TXT / EPUB support',
      language: 'German to Russian lookup',
      flow: 'Designed for deep reading flow',
    },
  },
  reader: {
    badge: 'Reader workspace',
    title: 'Local reader',
    subtitle: 'Upload a file and start reading instantly.',
    ctaComingSoon: 'Open reader',
  },
  readerWorkspace: {
    badge: 'Local Reader',
    title: 'Open your book and stay in flow',
    subtitle:
      'Upload a local file and continue in a focused reading layout with instant mock translation.',
    dragActiveSubtitle: 'Drop the file to open the book.',
    parsingSubtitle: 'Preparing the book locally. This takes a moment.',
    uploadCta: 'Upload book',
    parsingCta: 'Parsing book',
    tryDemoCta: 'Try demo',
    supportedFormats: 'Supported formats: TXT, MD, HTML, EPUB, FB2',
    dragActiveHint: 'Drop the file to open the book',
    noBackendHint: 'Everything works locally in your browser. No backend, no external APIs.',
    chapter: 'Chapter',
    pageLabel: 'Page {{current}} / {{total}}',
    prevPage: 'Prev',
    nextPage: 'Next',
    loadMore: 'Load more text',
    epubHint: 'EPUB chapters are preserved for calm chapter-by-chapter reading.',
    translationPanel: 'Translation',
    errors: {
      unsupported_format: 'This format is not supported yet. Use TXT, MD, HTML, EPUB, or FB2.',
      empty_content: 'This file does not contain readable text.',
      parse_failed: 'Unable to parse this file. Try another file version.',
      corrupted_epub: 'This EPUB looks corrupted and cannot be opened.',
      image_only_epub:
        'This book appears to contain mostly images or scanned pages, so readable text could not be extracted.',
      file_too_large: 'This file is too large for local MVP parsing right now.',
    },
  },
  demoReader: {
    title: 'Evening Walk in Berlin',
    headerHint: 'Click words or select a short phrase to see translation.',
    panelTitle: 'Translation',
    emptyState: 'Select a word or a short phrase to open a translation card.',
    selectedLabel: 'Selected',
    russianLabel: 'Russian',
    quickTranslation: 'Quick translation',
    hoverHint: 'Hover a word for quick translation, or click for instant result.',
    multiSelectOff: 'Select multiple words',
    multiSelectOn: 'Multiple selection enabled',
    multiSelectHint: 'Click words to compose a phrase. Translation updates instantly.',
    clearSelection: 'Clear selection',
    selectedPhraseLabel: 'Selected phrase:',
    translationUnavailable: 'Local translation is not available yet',
    translationHint: 'Try another word or shorter phrase.',
    autoGeneratedNote: 'Local dictionary entry.',
  },
  languageSwitcher: {
    en: 'EN',
    ru: 'RU',
  },
} as const

export default enCommon
